### ISSUE TITLE
A LICENSE question

### ISSUE THREAD

**Issue by Totktonada** [fab13n/checks#2]
@fab13n and @MelomanCool, aren't you mind if we'll license a derived work under the MIT license terms?

It is here: https://github.com/tarantool/checks

Something weird occurs in the past: someone copies your project without marking it as a fork and adds a LICENSE without your agreement (and, moreover, give copyright to Google by a mistake). I'm sorry.

**Comment by fab13n** [comment]
Hi,

this work has been written by me and split from LuaSched, itself under MIT licence. It's been my mistake to forget copying the licence, but it was indeed intended to be released under MIT licence.

I'll clarify this by adding a licence file in my repo.

**Comment by fab13n** [comment]
Actually what I wrote is wrong, this work has been released by my former employer under the Eclipse Public License v1.0, as indicated in checks.c.

I've inserted the correct LICENSE.md file in my repository.

**Comment by fab13n** [comment]
Thanks to @Totktonada for figuring out the licensing situation. This code is a direct extract from luasched https://github.com/SierraWireless/luasched, licensed both under MIT and EPL. I've updated the license here as MIT, as it's strictly more permissive than EPL.

**Comment by Totktonada** [comment]
Nice, thanks!

I have no more questions about licenses, so I'll close the issue.
